/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university;
import java.sql.*;
 
import javax.swing.JOptionPane;

/**
 *
 * @author nrath
 */
public class EditUnivDB extends javax.swing.JFrame {
int Tables; //1 refers to Department Table, 2 to Course Table
int Actions;//1 refers to Insert, 2 to Delete
String Command; //Insert Command, Delete Command

    /**
     * Creates new form EditUnivDB
     */
    public EditUnivDB() {
        initComponents();
       //DeleteQueryTextBox.setVisible(false); //Do not show this TextBox Initially. Show it when there is Delete
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        InsertRadioBtn = new javax.swing.JRadioButton();
        DeleteRadioBtn = new javax.swing.JRadioButton();
        DeptRadioBtn = new javax.swing.JRadioButton();
        CourseRadioBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DeptIdText = new javax.swing.JTextField();
        DeptNameText = new javax.swing.JTextField();
        DeptLocText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Execute = new javax.swing.JButton();
        DeleteQueryTextBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Editor: University DB");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        InsertRadioBtn.setText("Insert");
        InsertRadioBtn.setToolTipText("");
        InsertRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertRadioBtnActionPerformed(evt);
            }
        });

        DeleteRadioBtn.setText("Delete");
        DeleteRadioBtn.setToolTipText("");
        DeleteRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRadioBtnActionPerformed(evt);
            }
        });

        DeptRadioBtn.setText("Department");
        DeptRadioBtn.setToolTipText("");
        DeptRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptRadioBtnActionPerformed(evt);
            }
        });

        CourseRadioBtn.setText("Courses");
        CourseRadioBtn.setToolTipText("");
        CourseRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseRadioBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Tables");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Actions");
        jLabel4.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 153));
        jButton1.setText("Exit");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DeptIdText.setText("DeptId");
        DeptIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptIdTextActionPerformed(evt);
            }
        });

        DeptNameText.setText("DeptName");
        DeptNameText.setToolTipText("");

        DeptLocText.setText("DeptLoc");
        DeptLocText.setToolTipText("");

        jLabel2.setText("Dep Id");

        jLabel5.setText("Name");
        jLabel5.setToolTipText("");

        jLabel6.setText("Loc");

        Execute.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Execute.setForeground(new java.awt.Color(0, 0, 153));
        Execute.setText("Execute");
        Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteActionPerformed(evt);
            }
        });

        DeleteQueryTextBox.setToolTipText("Please Type the Query for Deletion here.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeptRadioBtn)
                            .addComponent(CourseRadioBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeleteRadioBtn)
                                    .addComponent(InsertRadioBtn))
                                .addGap(29, 29, 29))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(Execute)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 267, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeptLocText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(430, 430, 430))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeptNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeptIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteQueryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 159, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeptRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CourseRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeptIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeptNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeptLocText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteRadioBtn)
                            .addComponent(Execute))
                        .addGap(27, 27, 27)
                        .addComponent(DeleteQueryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeptIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptIdTextActionPerformed

    private void DeptRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptRadioBtnActionPerformed
        // TODO add your handling code here:
        Tables = 1;
        CourseRadioBtn.setSelected(false);
    }//GEN-LAST:event_DeptRadioBtnActionPerformed

    private void CourseRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseRadioBtnActionPerformed
        // TODO add your handling code here:
        Tables=2;
        DeptRadioBtn.setSelected(false);
    }//GEN-LAST:event_CourseRadioBtnActionPerformed

    private void InsertRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertRadioBtnActionPerformed
        // TODO add your handling code here:
        Actions=1;
        DeleteRadioBtn.setSelected(false);
    }//GEN-LAST:event_InsertRadioBtnActionPerformed

    private void DeleteRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRadioBtnActionPerformed
        // TODO add your handling code here:
        try {
            
        
        Actions=2;
        InsertRadioBtn.setSelected(false);
        DeptRadioBtn.setSelected(false);
        CourseRadioBtn.setSelected(false);
        //System.out.println("Comes into Delete Radio Button.");
      // DeleteQueryTextBox.setVisible(true); 
      // DeleteQueryTextBox.setVisible(true); 
       //Jframe.setVisible(true);
       // EditUnivDB.AccessibleJFrame.s setVisible(true);
       // DeleteOnQuery();
       if  (DeleteRadioBtn.isSelected())
        JOptionPane.showMessageDialog(null, "Please Ensure that a Correct Delete Statement is entered in the TextBox.");
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_DeleteRadioBtnActionPerformed

    /*******************************************************
     * ******************************************************
     */
    private void DeleteOnQuery() //JDBC
    {
        try{
                   String query = null;
                    System.out.println("Comes into try of DeleteOnQuery");
                   // DeleteQueryTextBox.setVisible(true); 
                   // while (query != null)
                        query = DeleteQueryTextBox.getText();
                    System.out.println(query);
        
                    Class.forName("com.mysql.jdbc.Driver");  //load and register the driver
                           
                        
                                
                     Connection  con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/university","root","root");  //establish the connection
                                
                                 PreparedStatement pst = con.prepareStatement(query);
                                 //pst.setString(1, DeptIdText.getText());
                                
                                 pst.execute();
                                 con.close();
                                 pst.close();
                                 JOptionPane.showMessageDialog(null, "Row Deletion Suuccessful !!!");
                                 DeleteQueryTextBox.setVisible(false);
        } //End of try
        
        catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, "Some issue in Deletion. Error !!!");
        }//End of Catch
        
    }//End of DeleteOnQuery
    
    private void ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteActionPerformed
        // TODO add your handling code here:
       // import java.sql.*;
        switch(Tables){
            
            case 1: //Department Table
            
                switch(Actions) {
                    
                    case 1: //Insert
                        /******************************************************/
                        /* Inserting into Dept Table */
                        
                        /*
                         JDBC
                        
                         */
                         try
                         {
                                System.out.println("\nComing to Department Insert....");
                                // Class.forName("com.mysql.jdbc.Driver");
                                Class.forName("com.mysql.jdbc.Driver");  //load and register the driver
                        
                                 System.out.println("\nComing out after Registration");
                        
                                //  Connection  con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/rathvsm2020","root","ruas");  //establish the connection
                                System.out.println("\nComing out after Connection");
                                Connection  con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/university","root","root");  //establish the connection
                                // Statement st=con.createStatement();  // create statement object
                                Command = "Insert into Department (Id, Name, Loc) values (?,?,?)";
                                 // ResultSet rs=st.executeQuery(query);
                                // PutRsInTable (rs); //Function call for putting the Result Set in the Table
                                 PreparedStatement pst = con.prepareStatement(Command);
                                 //pst.setString(1, DeptIdText.getText());
                                 pst.setInt(1, Integer.parseInt(DeptIdText.getText()));
                                 pst.setString(2, DeptNameText.getText());
                                 pst.setString(3, DeptLocText.getText());
                                 pst.execute();
                                 
                       
                                 //  System.out.println(name);
                                   con.close();   //close the connection
                                   pst.close();
                                   
                                   JOptionPane.showMessageDialog(null, "Row Inserted into Department Table.....");
                       // st.close();
                         }//End of try
                         catch(Exception e)
                         {
                             // System.out.println("Error Occured while trying to insrt into Department Table !!!");
                             JOptionPane.showMessageDialog(null, "Error  Inserting into Department Table.....");
                             
                         }
                        
                                              
                        
                        break;
                        
                    case 2://Delete
                        //There will be no table wise delete
                        
                       // DeleteOnQuery();
                        break;
                        
                    default: 
                        JOptionPane.showMessageDialog(null, "Appears No Action for Department Table has been Selected.");
                    
                }//Switch Actions
                
                break;
                
                
            case 2: //Course Table
                
                switch(Actions){
                    
                    case 1: //Insert
                        
                        break;
                     
                    case 2: //Delete
                         //DeleteOnQuery();
                        
                        break;
                        
                    default: 
                        JOptionPane.showMessageDialog(null, "Appears No Action for Course Table has been Selected."); 
                    
                }//End of Actions
                
                break;
                
            default: 
                if (Actions==1)
                JOptionPane.showMessageDialog(null, "Appears No Table has been Selected.");
            
        }//End of Switch Tables
       
        if  (Actions == 2)
            DeleteOnQuery();
               
            
    }//GEN-LAST:event_ExecuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUnivDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUnivDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUnivDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUnivDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUnivDB().setVisible(true);
}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CourseRadioBtn;
    private javax.swing.JTextField DeleteQueryTextBox;
    private javax.swing.JRadioButton DeleteRadioBtn;
    private javax.swing.JTextField DeptIdText;
    private javax.swing.JTextField DeptLocText;
    private javax.swing.JTextField DeptNameText;
    private javax.swing.JRadioButton DeptRadioBtn;
    private javax.swing.JButton Execute;
    private javax.swing.JRadioButton InsertRadioBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
